Add test to verify that AR has been found
git-svn-id: https://svn.apache.org/repos/asf/xerces/c/trunk@504184 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -19931,6 +19931,13 @@ if eval "test \"`echo '$ac_cv_prog_cc_'${ac_cc}_c_o`\" != yes"; then
 fi
 
 
+if test x$AR = xfalse; then
+  { { echo "$as_me:$LINENO: error: Cannot find a valid 'ar' tool" >&5
+echo "$as_me: error: Cannot find a valid 'ar' tool" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+
 # Checks for libraries.
 
 { echo "$as_me:$LINENO: checking for socket in -lsocket" >&5
