This commit was manufactured by cvs2svn to create tag 'Xerces-C_1_0_0'.
git-svn-id: https://svn.apache.org/repos/asf/xerces/c/tags/Xerces-C_1_0_0@171462 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/samples/runConfigure b/samples/runConfigure
--- a/samples/runConfigure
+++ b/samples/runConfigure
@@ -58,8 +58,44 @@
 # 
 #
 # $Log$
-# Revision 1.1  1999/11/09 01:09:26  twl
-# Initial revision
+# Revision 1.3  1999/12/02 18:10:51  dirkx
+# Changed exit codes from -1 to '1'. Added indirection.
+#
+# Date: Thu, 2 Dec 1999 17:47:39 +0000
+# From: Jonathan McDowell <noodles@earth.li>
+# Reply-To: xerces-dev@xml.apache.org
+# To: xerces-dev@xml.apache.org, rahulj@apache.org
+# Subject: Re: runConfigure script & bash
+#
+#
+# On Mon, Nov 29, 1999 at 10:29:13AM -0800, Rahul Jain wrote:
+#
+# > > I'm quite happy to produce a patch that makes it work under both
+# > > FreeBSD's sh and bash - I would assume this would work under most sh
+# > > like shells.
+# > Please post the changes for FreeBSD and I will test the changes on
+# > other unix's and do the integration.
+#
+# I sat down to do this today and found that it can be trivially fixed by
+# changing all the "exit -1" instances to "exit 1" - it seems the /bin/sh
+# with FreeBSD doesn't like negative result codes. It seems a bit
+# pointless to submit a patch for this, so can someone with CVS access
+# change this please?
+#
+# J.
+#
+# --
+#
+# PR:
+# Obtained from:
+# Submitted by:
+# Reviewed by:
+#
+# Revision 1.2  1999/11/12 19:12:40  abagchi
+# Changed instances of XML4CROOT to XERCESCROOT
+#
+# Revision 1.1.1.1  1999/11/09 01:09:26  twl
+# Initial checkin
 #
 # Revision 1.4  1999/11/08 20:43:34  rahul
 # Swat for adding in Product name and CVS comment log variable.
@@ -82,24 +118,26 @@ usage()
     echo "       -h (get help on the above commands)"
 }
 
+ERROR_EXIT_CODE=1
+
 if test ${1}o = "o"; then
    usage
-   exit -1
+   exit ${ERROR_EXIT_CODE}
 fi
 
-if test ${XML4CROOT}o = "o"; then
-   echo ERROR : You have not set your XML4CROOT environment variable
+if test ${XERCESCROOT}o = "o"; then
+   echo ERROR : You have not set your XERCESCROOT environment variable
    echo Though this environment variable has nothing to do with creating makefiles,
    echo this is just a general warning to prevent you from pitfalls in future. Please
-   echo set an environment variable called XML4CROOT to indicate where you installed
-   echo the XML4C files, and run this command again to proceed. See the documentation
+   echo set an environment variable called XERCESCROOT to indicate where you installed
+   echo the XERCES-C files, and run this command again to proceed. See the documentation
    echo for an example if you are still confused.
-   exit -1
+   exit ${ERROR_EXIT_CODE}
 fi
 
 if test $1 = "-h"; then
    usage
-   exit -1
+   exit ${ERROR_EXIT_CODE}
 fi
 
 # Get the command line parameters
@@ -107,7 +145,7 @@ set -- `getopt p:c:x:dm:n:t:r:l:z:h $*`
 if [ $? != 0 ]
    then
    usage
-   exit -1
+   exit ${ERROR_EXIT_CODE}
 fi
 
 # Set up the default values for each parameter
@@ -133,7 +171,7 @@ for i in $*
 
    -h)
         usage
-        exit -1;;
+        exit ${ERROR_EXIT_CODE};;
 
    --)
         shift; break;;
@@ -159,7 +197,7 @@ case $platform in
        ;;
    *)
       echo "I do not recognize the platform '$platform'. Please type '${0} -h' for help."
-      exit -1;;
+      exit ${ERROR_EXIT_CODE};;
 esac
 
 # Set the C compiler and C++ compiler environment variables
@@ -200,7 +238,7 @@ rm -f config.status
 
 echo
 echo If the result of the above commands look OK to you, go to the directory
-echo ${XML4CROOT}/src and type \"make\" to make the XML4C system.
+echo ${XERCESCROOT}/src and type \"make\" to make the XERCES-C system.
 
 exit 0;
 
diff --git a/src/runConfigure b/src/runConfigure
--- a/src/runConfigure
+++ b/src/runConfigure
@@ -58,8 +58,62 @@
 # 
 #
 # $Log$
-# Revision 1.1  1999/11/09 01:02:57  twl
-# Initial revision
+# Revision 1.9  1999/12/03 01:19:11  rahulj
+# Split export statements into two. assignment and then export. Solaris is happy now
+#
+# Revision 1.8  1999/12/02 18:10:51  dirkx
+# Changed exit codes from -1 to '1'. Added indirection.
+#
+# Date: Thu, 2 Dec 1999 17:47:39 +0000
+# From: Jonathan McDowell <noodles@earth.li>
+# Reply-To: xerces-dev@xml.apache.org
+# To: xerces-dev@xml.apache.org, rahulj@apache.org
+# Subject: Re: runConfigure script & bash
+#
+#
+# On Mon, Nov 29, 1999 at 10:29:13AM -0800, Rahul Jain wrote:
+#
+# > > I'm quite happy to produce a patch that makes it work under both
+# > > FreeBSD's sh and bash - I would assume this would work under most sh
+# > > like shells.
+# > Please post the changes for FreeBSD and I will test the changes on
+# > other unix's and do the integration.
+#
+# I sat down to do this today and found that it can be trivially fixed by
+# changing all the "exit -1" instances to "exit 1" - it seems the /bin/sh
+# with FreeBSD doesn't like negative result codes. It seems a bit
+# pointless to submit a patch for this, so can someone with CVS access
+# change this please?
+#
+# J.
+#
+# --
+#
+# PR:
+# Obtained from:
+# Submitted by:
+# Reviewed by:
+#
+# Revision 1.7  1999/12/01 17:16:16  rahulj
+# Added support for IRIX 6.5.5 using SGI MIPSpro C++ 7.3 and 7.21 generating 32 bit objects. Changes submitted by Marc Stuessel
+#
+# Revision 1.6  1999/11/24 23:21:42  rahulj
+# Now works under HPUX 10.20 with CC and aCC, with ICU and native
+distclean target now remove and remaining Makefile(s)
+clean target now removes the template repository directory
+#
+# Revision 1.5  1999/11/23 01:59:33  rahulj
+# Code now works under HPUX 11. Tested inmemory message loader.
+Revamped makefiles. Builds with both DCE threads as well as pthread libraries.
+#
+# Revision 1.4  1999/11/17 22:36:33  rahulj
+# Code works with ICU transcoding service
+#
+# Revision 1.3  1999/11/12 20:38:50  rahulj
+# Replaced XML4CROOT with XERCESCROOT.
+#
+# Revision 1.1.1.1  1999/11/09 01:02:57  twl
+# Initial checkin
 #
 # Revision 1.4  1999/11/08 20:44:09  rahul
 # Swat for adding in Product name and CVS comment log variable.
@@ -67,20 +121,30 @@
 #
 
 #
-# runConfigure : This script will run the "configure" script for the appropriate platform
-# Only supported platforms are recognized
+# runConfigure:
+#    This script will run the "configure" script for the appropriate
+#    platform. Only supported platforms are recognized.
+#
+# The following variables are defined and exported at the end of this
+# script.
+#
+# LIBS
+# LDFLAGS
+# CXXFLAGS
+# TRANSCODER
+#
 
 usage()
 {
     echo "runConfigure: Helper script to run \"configure\" for one of the supported platforms"
     echo "Usage: runConfigure \"options\""
     echo "       where options may be any of the following:"
-    echo "       -p <platform> (accepts 'aix', 'linux', 'solaris', 'hp-10', 'hp-11')"
-    echo "       -c <C compiler name> (e.g. gcc or xlc)"
-    echo "       -x <C++ compiler name> (e.g. g++ or xlC)"
+    echo "       -p <platform> (accepts 'aix', 'linux', 'solaris', 'hp-10', 'hp-11', 'irix')"
+    echo "       -c <C compiler name> (e.g. gcc, cc, xlc)"
+    echo "       -x <C++ compiler name> (e.g. g++, CC, xlC)"
     echo "       -d (specifies that you want to build debug version)"
-    echo "       -m <message loader> can be 'inmem', 'icu' or 'iconv'"
-    echo "       -n <net accessor> can be 'fileonly' or 'libwww'"
+    echo "       -m <message loader> can be 'inmem', 'icu', 'iconv'"
+    echo "       -n <net accessor> can be 'fileonly', 'libwww'"
     echo "       -t <transcoder> can be 'icu' or 'native'"
     echo "       -r <thread option> can be 'pthread' or 'dce' (only used on HP-11)"
     echo "       -l <extra linker options>"
@@ -88,24 +152,26 @@ usage()
     echo "       -h (to get help on the above commands)"
 }
 
+ERROR_EXIT_CODE=1
+
 if test ${1}o = "o"; then
    usage
-   exit -1
+   exit ${ERROR_EXIT_CODE}
 fi
 
-if test ${XML4CROOT}o = "o"; then
-   echo ERROR : You have not set your XML4CROOT environment variable
+if test ${XERCESCROOT}o = "o"; then
+   echo ERROR : You have not set your XERCESCROOT environment variable
    echo Though this environment variable has nothing to do with creating makefiles,
    echo this is just a general warning to prevent you from pitfalls in future. Please
-   echo set an environment variable called XML4CROOT to indicate where you installed
-   echo the XML4C files, and run this command again to proceed. See the documentation
+   echo set an environment variable called XERCESCROOT to indicate where you installed
+   echo the XERCES-C files, and run this command again to proceed. See the documentation
    echo for an example if you are still confused.
-   exit -1
+   exit ${ERROR_EXIT_CODE}
 fi
 
 if test $1 = "-h"; then
    usage
-   exit -1
+   exit ${ERROR_EXIT_CODE}
 fi
 
 # Get the command line parameters
@@ -113,13 +179,13 @@ set -- `getopt p:c:x:dm:n:t:r:l:z:h $*`
 if [ $? != 0 ]
    then
    usage
-   exit -1
+   exit ${ERROR_EXIT_CODE}
 fi
 
 # Set up the default values for each parameter
 debug=off                # by default debug is off
 transcoder=native        # by default use native transcoder
-msgloader=iconv          # by default use native transcoder
+msgloader=inmem          # by default use native transcoder
 netaccessor=fileonly     # by default use fileonly
 
 for i in $*
@@ -157,7 +223,7 @@ for i in $*
    
    -h) 
         usage
-        exit -1;; 
+        exit ${ERROR_EXIT_CODE};; 
    
    --) 
         shift; break;; 
@@ -170,149 +236,195 @@ echo "C Compiler: $ccompiler"
 echo "C++ Compiler: $cppcompiler"
 echo "Extra compile options: $compileroption"
 echo "Extra link options: $linkeroption"
-if test $debug = "off"; then
-    echo "Debug is OFF"
-    debugflag="-w -O";
-else
-    echo "Debug is ON"
-    debugflag="-g";
-fi
 echo "Message Loader: $msgloader"
 echo "Net Accessor: $netaccessor"
 echo "Transcoder: $transcoder"
 echo "Thread option: $thread"
 
+
+#
 # Now check if the options are correct or not, bail out if incorrect
+#
+
 case $platform in
-   aix | linux | solaris | hp-10 | hp-11)
+   aix | linux | solaris | hp-10 | hp-11 | irix)
        # platform has been recognized
        ;;
    *)
       echo "I do not recognize the platform '$platform'. Please type '${0} -h' for help."
-      exit -1;;
+      exit ${ERROR_EXIT_CODE};;
 esac
 
-# Now check for the transcoder
-transcoderoption="-DXML_USE_NATIVE_TRANSCODER"
+
+#
+# Enable debugging or not...
+#
+
+if test $debug = "off"; then
+    echo "Debug is OFF"
+    debugflag="-O";
+else
+    echo "Debug is ON"
+    debugflag="-g";
+fi
+
+
+
+#
+# Check for the threading option only for hp-11
+#
+
+threadingLibs="-lpthread"
+if test $platform = "hp-11"; then
+    if test $thread; then
+    case $thread in
+       pthread)
+           ;;
+    
+       dce)
+           threadingLibs="-lcma";
+           threadingDefines="-D_PTHREADS_DRAFT4 -DXML_USE_DCE" ;;
+    
+       *)
+           echo "I do not recognize the thread option '$thread'. Please type '${0} -h' for help."
+           exit ${ERROR_EXIT_CODE};;
+    esac
+    fi
+elif test $platform = "aix"; then
+    threadingLibs="-lpthreads"
+elif test $platform = "hp-10"; then
+    threadingLibs="-lcma"
+    threadingDefines="-DXML_USE_DCE"
+fi
+
+
+#
+# Now check for what kind of transcoding service is desired.
+#
+
+transcodingDefines="-DXML_USE_NATIVE_TRANSCODER"
 TRANSCODER=NATIVE
 
 if test $transcoder; then
 case $transcoder in
    icu)
-       transcoderoption="-DXML_USE_ICU_TRANSCODER" ;
-       TRANSCODER=ICU ;;
+       if test -z $ICUROOT; then
+           echo '***Error*** ICUROOT environment variable not defined. Exiting...';
+           exit ${ERROR_EXIT_CODE};
+       fi
+       transcodingDefines="-DXML_USE_ICU_TRANSCODER -I${ICUROOT}/include";
+       transcodingLibs="-L${ICUROOT}/lib -licu-uc";
+       TRANSCODER=ICU;;
 
    native)
-       transcoderoption="-DXML_USE_NATIVE_TRANSCODER" ;
-       TRANSCODER=NATIVE ;;
+       ;;
 
    *)
       echo "I do not recognize the transcoder option '$transcoder'. Please type '${0} -h' for help."
-      exit -1;;
+      exit ${ERROR_EXIT_CODE};;
 esac
 fi
 
 export TRANSCODER
 
+
+#
 # Now check for the message loader
-MESSAGELOADER=INMEM;   # By default use in-memory
-msgloaderoption="-DXML_USE_INMEM_MESSAGELOADER"
+#
+
+MESSAGELOADER=INMEM         # By default use in-memory
+msgloaderDefines="-DXML_USE_INMEM_MESSAGELOADER"
 
 if test $msgloader ; then
 case $msgloader in
    icu)
+       if test -z $ICUROOT ; then
+           echo '***Error*** ICUROOT environment variable not defined. Exiting...';
+           exit ${ERROR_EXIT_CODE};
+       fi
        MESSAGELOADER=ICU;
-       msgloaderoption="-DXML_USE_ICU_MESSAGELOADER" ;;
+       msgloaderDefines="-DXML_USE_ICU_MESSAGELOADER" ;;
 
    inmem)
-       MESSAGELOADER=INMEM;
-       msgloaderoption="-DXML_USE_INMEM_MESSAGELOADER" ;;
+       ;;
 
    iconv)
        MESSAGELOADER=ICONV;
-       msgloaderoption="-DXML_USE_ICONV_MESSAGELOADER" ;;
+       msgloaderDefines="-DXML_USE_ICONV_MESSAGELOADER" ;;
 
    *)
-      echo "I do not recognize the message loader option '$msgloader'. Please type '${0} -h' for help."
-      exit -1;;
+      echo "I do not recognize the message loader option '$msgloader'. Please type '${0} -h' for help.";
+      exit ${ERROR_EXIT_CODE};;
 esac
 fi
 
 export MESSAGELOADER
 
-# Check for the threading option only for hp-11
-if test $platform = "hp-11"; then
-    if test $thread; then
-    case $thread in
-       pthread)
-           threadingoption="-DXML_USE_PTHREAD" ;;
-    
-       dce)
-           threadingoption="-DXML_USE_DCE" ;;
-    
-       *)
-          echo "I do not recognize the thread option '$thread'. Please type '${0} -h' for help."
-          exit -1;;
-    esac
-    else
-          echo "You must provide a thread option for HPUX-11". Cannot proceed any further.
-          exit -1;
-    fi
+
+
+
+#
+# Check for the type of net accessor
+#
+
+USELIBWWW=0;                   # By default use file-only
+if test $netaccessor ; then
+case $netaccessor in
+   fileonly)
+       netaccessorDefines="" ;;
+
+   libwww)
+       if test -z ${LIBWWWROOT} ; then
+           echo "You have not defined your LIBWWWROOT environment variable. Cannot proceed further ..."
+           exit ${ERROR_EXIT_CODE};
+       fi
+       netaccessorDefines="-DXML_USE_NETACCESSOR_LIBWWW -I${LIBWWWROOT}/include" ;
+       netaccessorLibs="-L${LIBWWWROOT}/lib -lwww";
+       USELIBWWW=1;; 
+
+   *)
+      echo "I do not recognize the netaccessor option '$netaccessor'. Please type '${0} -h' for help."
+      exit ${ERROR_EXIT_CODE};;
+esac
 fi
 
+export USELIBWWW
+
+
+
+#
 # Set the C compiler and C++ compiler environment variables
-CC=$ccompiler; export CC
-CXX=$cppcompiler; export CXX
+#
 
 case $cppcompiler in
-   xlC | xlc | xlC_r | xlc_r)
-       LDFLAGS="-lC"; export LDFLAGS
-       LIBS="-L/usr/lpp/xlC/lib"; export LIBS ;;
-
-   g++ | c++)
-       LDFLAGS="-lc"; export LDFLAGS
-       LIBS="-L/usr/local/lib"; export LIBS ;;
-
-   cc | CC)
-       LDFLAGS="-lC"; export LDFLAGS
-       LIBS="-L/usr/lib -L/usr/ccs/lib"; export LIBS ;;
-
-   acc | aCC)
-       LDFLAGS="-lC"; export LDFLAGS
-       LIBS="-L/usr/lib -L/opt/aCC/lib"; export LIBS ;;
+   xlC | xlc | xlC_r | xlc_r | g++ | c++ | cc | CC | aCC)
+      ;;
 
    *)
       echo "I do not recognize the C++ compiler '$cppcompiler'. Continuing anyway ..." 
       ;;
 esac
 
-USELIBWWW=0;   # By default use file-only
-# Check for the type of net accessor
-if test $netaccessor ; then
-case $netaccessor in
-   fileonly)
-       netaccessoroption="" ;;
+CC="$ccompiler"
+export CC
 
-   libwww)
-       if test -z ${LIBWWWROOT} ; then
-           echo "You have not defined your LIBWWWROOT environment variable. Cannot proceed further ..."
-           exit -1;
-       fi
-       netaccessoroption="-DXML_USE_NETACCESSOR_LIBWWW -I${LIBWWWROOT}/include" ;
-       LIBS="$LIBS -L${LIBWWWROOT}/lib -lwww";
-       USELIBWWW=1;; 
+CXX="$cppcompiler"
+export CXX
 
-   *)
-      echo "I do not recognize the netaccessor option '$netaccessor'. Please type '${0} -h' for help."
-      exit -1;;
-esac
-fi
 
-export USELIBWWW;
-
+#
 # Set the extra C and C++ compiler flags
-CXXFLAGS="$debugflag $compileroption $transcoderoption $msgloaderoption $threadingoption $netaccessoroption"; export CXXFLAGS
-CFLAGS="$debugflag $compileroption $transcoderoption $msgloaderoption $threadingoption $netaccessoroption"; export CFLAGS
+#
+
+CXXFLAGS="$debugflag $transcodingDefines $msgloaderDefines $threadingDefines $netaccessorDefines"
+export CXXFLAGS
+
+CFLAGS="$debugflag $transcodingDefines $msgloaderDefines $threadingDefines $netaccessorDefines"
+export CFLAGS
+
+LIBS="$transcodingLibs $threadingLibs $netaccessorLibs"
+export LIBS
+
 
 echo
 rm -f config.cache
@@ -322,7 +434,7 @@ rm -f config.status
 
 echo
 echo If the result of the above commands look OK to you, go to the directory
-echo ${XML4CROOT}/src and type \"make\" to make the XML4C system.
+echo ${XERECSCROOT}/src and type \"make\" to make the XERECS-C system.
 
-exit 0;
+exit  0;
 
