Enabling libWWW NetAccessor support under UNIX. Tested with latest tarball of libWWW (w3c-libwww-5.3.2) under RedHat Linux 6.1.  Added by Martin Kalen.
There is one MAJOR problem with the use of libwww and the patches
below, which someone with knowledge of libwww filters etc. might want
to look into. Default behavior for content-type text/xml is to consume
all xml data before it reaches the simple HTML presenter. Hence, only
files with content-type text/html will actually reach the xerces-c
library. If you have a *.xml file on the webbserver, processing of the
file will throw an exception stating "The main XML document cannot be
empty" (correct in a xerces point of view since if you enable debug
build you will see that libwww "eats" all text/xml).

See "Diffs for enabling libWWW NetAccessor support under UNIX" posted in March 1, 2001
in the xerces-c-dev mailing list for further information.


git-svn-id: https://svn.apache.org/repos/asf/xerces/c/trunk@172553 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/src/runConfigure b/src/runConfigure
--- a/src/runConfigure
+++ b/src/runConfigure
@@ -377,17 +377,17 @@ case $netaccessor in
 
    libwww)
        NETACCESSOR=LibWWW
-       if test -z ${LIBWWWROOT} ; then
-           echo "You have not defined your LIBWWWROOT environment variable. Cannot proceed further ..."
+       if test -z "`libwww-config --libs 2>/dev/null`" ; then
+           echo "Netaccessor is libwww, but libwww-config is not found. Cannot proceed further."
            exit ${ERROR_EXIT_CODE};
        fi
-       netaccessorDefines="-DXML_USE_NETACCESSOR_LIBWWW -I${LIBWWWROOT}/include" ;
-       netaccessorLibs="-L${LIBWWWROOT}/lib -lwww";
+       netaccessorDefines="-DXML_USE_NETACCESSOR_LIBWWW `libwww-config --cflags`"
+       netaccessorLibs="`libwww-config --libs`"
        USELIBWWW=1;;
 
    *)
-      echo "I do not recognize the netaccessor option '$netaccessor'. Please type '${0} -h' for help."
-      exit ${ERROR_EXIT_CODE};;
+       echo "I do not recognize the netaccessor option '$netaccessor'. Please type '${0} -h' for help."
+       exit ${ERROR_EXIT_CODE};;
 esac
 fi
 
@@ -470,4 +470,3 @@ echo If the result of the above commands look OK to you, go to the directory
 echo ${XERCESCROOT}/src and type \"gmake\" to make the XERCES-C system.
 
 exit  0;
-
